### ISSUE TITLE
Clock text update delay

### ISSUE THREAD

**Issue by Tokhiya** [GeekMagicClock/smalltv#13]
hello!

i have updated gif file . it consists 2 frames and every frame is delay time 3 seconds.

after updated gif on device . clock screen is shown every 3 seconds updated.

So, It is displayed in 3-second skips.

is fixed it in new version?? or gif file with more than 2 frames or delay times not supported?

**Comment by GeekMagicClock** [comment]
Hi, I think for gif display, delay time is supported, but since it would delay for 3 seconds, the screen will be delayed for 3 seconds too, and then refresh the display of seconds.
