### ISSUE TITLE
Uploaded the firmware for Smalltv ultra, no function now....

### ISSUE THREAD

**Issue by Toni007de** [GeekMagicClock/smalltv#20]
Hello!

I wanted to download the firmware of a Smalltv ultra to a normal Smalltv. Now the screen stays black and there is no function. Then I connected a USB programmer and used the Espressiv Flash Tool. The firmware is downloading, but no function. What can I download to bring the device back to life?

Thank you in advance!

**Comment by GeekMagicClock** [comment]
Sorry, not supported.
