### ISSUE TITLE
How can I update this device firmware?

### ISSUE THREAD

**Issue by samueljake** [GeekMagicClock/smalltv#3]
![image](https://github.com/GeekMagicClock/smalltv/assets/146141628/4b44ad5c-b1db-4c1e-8685-81b17434bccc)
I tried many times.
I can not connect my device's ip address/update.

**Comment by Cabalist** [comment]
I'm also having this issue.

**Comment by GeekMagicClock** [comment]
Hi, seems the response is not from the clock, what version do you have?

**Comment by exampleex** [comment]
> ![image](https://user-images.githubusercontent.com/146141628/270812841-4b44ad5c-b1db-4c1e-8685-81b17434bccc.png) I tried many times. I can not connect my device's ip address/update.



> I'm also having this issue.

Try to access from the front page.
![Screenshot 2566-09-29 at 10 08 04](https://github.com/GeekMagicClock/smalltv/assets/21957372/4c393d5e-21fa-4469-87cb-879ea98985b6)

**Comment by GeekMagicClock** [comment]
> > ![image](https://user-images.githubusercontent.com/146141628/270812841-4b44ad5c-b1db-4c1e-8685-81b17434bccc.png) I tried many times. I can not connect my device's ip address/update.
> 
> > I'm also having this issue.
> 
> Try to access from the front page. ![Screenshot 2566-09-29 at 10 08 04](https://user-images.githubusercontent.com/21957372/271462712-4c393d5e-21fa-4469-87cb-879ea98985b6.png)

what verison do you have?

**Comment by exampleex** [comment]
> what verison do you have?

3.0.33

**Comment by GeekMagicClock** [comment]
1. For earlier versions, v3.0.x etc, please update to 3.0.33, that's stable and the latest, do not update to v3.1.0 or later, or the web pages will be not found.
2. For versions after v3.1.0, could be updated to v3.1.x.

**Comment by GeekMagicClock** [comment]
> > what verison do you have?
> 
> 3.0.33

What's the version before you update it to v3.0.33? I have tested v3.0.33, no such problem appeared

**Comment by exampleex** [comment]
> > > what verison do you have?
> > 
> > 
> > 3.0.33
> 
> What's the version before you update it to v3.0.33? I have tested v3.0.33, no such problem appeared

3.1.1

**Comment by nikopiko666** [comment]
> 1. For earlier versions, v3.0.x etc, please update to 3.0.33, that's stable and the latest, do not update to v3.1.0 or later, or the web pages will be not found.
> 2. For versions after v3.1.0, could be updated to v3.1.x.

how to update the firmware whe /update doesnt work?

**Comment by luhis** [comment]
I have v2.5.4, how do i update the firmware? soldering on a serial adapter is fine
