### ISSUE TITLE
Weather icon does not work propperly 

### ISSUE THREAD

**Issue by DJ-SNAHS** [GeekMagicClock/smalltv#30]
I have the latest firmware, but I can't view the weather icon. Is any way to view the weather icon correctly? Thanks.

![IMG_20240409_233322505](https://github.com/GeekMagicClock/smalltv/assets/166560765/dc5cb44c-fb62-49a8-9d67-c24d3c11d1be)
![IMG_20240409_233322505](https://github.com/GeekMagicClock/smalltv/assets/166560765/31b6785c-6477-4247-96b1-b09a5f2e1baa)
I only see a gray icon, no clouds, no rain, no sun...

**Comment by GeekMagicClock** [comment]
Hi, can you show me your settings of city? The city name should be displayed.
The gray circle means it is clear at night, when it comes to day time, the icon will be change to another one.

**Comment by DJ-SNAHS** [comment]
> Hi, can you show me your settings of city? The city name should be displayed. The gray circle means it is clear at night, when it comes to day time, the icon will be change to another one.

Yes, the city name appeared well, but for privacy reason I deleted it.  I'm going to chek if the gray circle change, I changed the city  code to another code reference. Thanks for the help, I will keep you informed.

**Comment by DJ-SNAHS** [comment]
Well I tested now, looks like the weather icon was freezed, I changed to another country and now it's working well I hope...  Thanks for the support.  My best greetings.

**Comment by GeekMagicClock** [comment]
Thanks for udpate back~
