### ISSUE TITLE
How to reset this device without browser gui?

### ISSUE THREAD

**Issue by msdos** [GeekMagicClock/smalltv#31]
My router died after I connected this device. Can I manually reset it, or flash it using esptool for example?

**Comment by GeekMagicClock** [comment]
Hi, which one is died?  What is displayed now?

**Comment by msdos** [comment]
My router. The GeekMagicClock is working fine. But since I can't access it anymore because of my router, I would like to reset to factory settings without the browser. Is it possible?

**Comment by GeekMagicClock** [comment]
Yes, try this:  Plug it off when the progress bar starting, repeat twice, the third time you power it on, it will enter into AP mode. You will get chance to re-configure it.

**Comment by msdos** [comment]
It worked! I think you should add this to the official website (the qr code card) that comes with the device.
