### ISSUE TITLE
About DST settings

### ISSUE THREAD

**Issue by tsuka72** [GeekMagicClock/smalltv#32]
I am using V3.0.33.
I set Tokyo as the city name, but daylight savings time is set and the time is displayed one hour ahead.
There is no DST setting item in V3.0.33, where can I set it?

**Comment by GeekMagicClock** [comment]
Hi, please disable the DST option.



At 2024-04-15 14:32:35, "tsuka72" ***@***.***> wrote:

I am using V3.0.33.
I set Tokyo as the city name, but daylight savings time is set and the time is displayed one hour ahead.
There is no DST setting item in V3.0.33, where can I set it?

**Comment by tsuka72** [comment]
Thank you very much.
I learned that No. 13 has a DST item.
I misunderstood that it was to be set with NTP items.
