### ISSUE TITLE
Do you know licence key?

### ISSUE THREAD

**Issue by Woo-Hwan** [GeekMagicClock/smalltv#9]
![1](https://github.com/GeekMagicClock/smalltv/assets/68598335/5953793e-bcf7-44b9-bf6c-2745000a208d)
![2](https://github.com/GeekMagicClock/smalltv/assets/68598335/310e6949-108e-41c9-9652-41933d5bd53d)
After updating to version 2.4.3 a few days ago, the same symptoms as in the picture occurred.

**Comment by GeekMagicClock** [comment]
Can you send the firmware file to me? I'll test it.

**Comment by Woo-Hwan** [comment]
> Can you send the firmware file to me? I'll test it.

[FW_SD2.4.3_1117.zip](https://github.com/GeekMagicClock/smalltv/files/13671378/FW_SD2.4.3_1117.zip)

**Comment by Woo-Hwan** [comment]
Please upload the initial firmware for the smalltv

**Comment by GeekMagicClock** [comment]
Hi I think it's not our product, it's a copy one, I can't help. Our case have round coner.
![image](https://github.com/GeekMagicClock/smalltv/assets/143304545/25469df3-f80b-443f-9747-e42f507ed644)

**Comment by ChocoChopy** [comment]
Same problem! After updating the firmware to 2.4.8, help set up the clock!
![1](https://github.com/GeekMagicClock/smalltv/assets/120978294/4a989757-e67e-4212-91dd-e29e3bfc33d4)


![2](https://github.com/GeekMagicClock/smalltv/assets/120978294/61bc9f0b-d482-443c-aed9-b3b044f87cc3)

**Comment by warst** [comment]
Did anyone have any luck with the license code issue? It appears we have purchased copies of the original device and the company decided to lock them with a license code which appears to be unobtainable! Is there a way we can flash these devices with different firmware that will allow us to repurpose them?

**Comment by warst** [comment]
> Same problem! After updating the firmware to 2.4.8, help set up the clock! ![1](https://private-user-images.githubusercontent.com/120978294/296489076-4a989757-e67e-4212-91dd-e29e3bfc33d4.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjI5ODEsIm5iZiI6MTcxNjA2MjY4MSwicGF0aCI6Ii8xMjA5NzgyOTQvMjk2NDg5MDc2LTRhOTg5NzU3LWU2N2UtNDIxMi05MWRkLWUyOWUzYmZjMzNkNC5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQyMDA0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMTdmMTRlNzZjNzg2NGI2ZjIyMTM3YjA1MDg5YmEzZDU4YWFjMmZiMzViOTA5NmYwMjE5MzU3YTcwY2E5ZGQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nGbvsZf4WN4rA4VklrFD5id_uGfhw4kuBy2jBbhxaxI)
> 
> ![2](https://private-user-images.githubusercontent.com/120978294/296489124-61bc9f0b-d482-443c-aed9-b3b044f87cc3.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjI5ODEsIm5iZiI6MTcxNjA2MjY4MSwicGF0aCI6Ii8xMjA5NzgyOTQvMjk2NDg5MTI0LTYxYmM5ZjBiLWQ0ODItNDQzYy1hZWQ5LWIzYjA0NGY4N2NjMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUxOFQyMDA0NDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03OWFhZjgzOTVkM2MyNWRiYmYzZjgzZDE5Mjc3ODU5ZDVhMTE2MzYxYzc2NzIyZjQ0NDliMmY0YzM1NGM4ODViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ab4rxzYDXke_dgL3FVtFMPZatuqXpY4IUDvevt8-y1k)

If you haven't got it yet, your activation code should be F6D427C32730

**Comment by warst** [comment]
> ![1](https://private-user-images.githubusercontent.com/68598335/289854759-5953793e-bcf7-44b9-bf6c-2745000a208d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjMxMDAsIm5iZiI6MTcxNjA2MjgwMCwicGF0aCI6Ii82ODU5ODMzNS8yODk4NTQ3NTktNTk1Mzc5M2UtYmNmNy00NGI5LWJmNmMtMjc0NTAwMGEyMDhkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIwMDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkNTJlODdiN2M1YTZiOGYwOWRjNjg4ZTFiMjEwZDI0NWQwODA1ZGE1ODI0ZGUxMGQzOGNmODdiZDljM2EyYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.eqp1we_bBWrdMb0J9MX9x-zTwmKgqQbmTGelJAEei2w) ![2](https://private-user-images.githubusercontent.com/68598335/289854787-310e6949-108e-41c9-9652-41933d5bd53d.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYwNjMxMDAsIm5iZiI6MTcxNjA2MjgwMCwicGF0aCI6Ii82ODU5ODMzNS8yODk4NTQ3ODctMzEwZTY5NDktMTA4ZS00MWM5LTk2NTItNDE5MzNkNWJkNTNkLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE4VDIwMDY0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg2NzdkZmExYjUzNjZkMmEwNjcyOGZhYjUwMzYzMzA2NGNlMDJmMTYzZjFiYzQyMjVhYmUyY2VmZmQzYzA2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5zRErYgwWKQ82g0MMaM8IZ0Xva0-uQ8piwK3bmBNywg) After updating to version 2.4.3 a few days ago, the same symptoms as in the picture occurred.

If you haven't got it yet, your activation code should be 8DE871B379BE

**Comment by warst** [comment]
> Did anyone have any luck with the license code issue? It appears we have purchased copies of the original device and the company decided to lock them with a license code which appears to be unobtainable! Is there a way we can flash these devices with different firmware that will allow us to repurpose them?

Send me a message or reply here with your MAC if you need a code.

**Comment by Bledule** [comment]
My MAC is: 40:91:51:58:A7:BC and Firmware is 2.5.4, please find my license password.
THX

**Comment by warst** [comment]
> My MAC is: 40:91:51:58:A7:BC and Firmware is 2.5.4, please find my license password. THX

C2B45FA7A44E

**Comment by Bledule** [comment]
thank you
______________________________________________________________
> Od: "Warren" ***@***.***>
> Komu: "GeekMagicClock/smalltv" ***@***.***>
> Datum: 23.07.2024 18:15
> Předmět: Re: [GeekMagicClock/smalltv] Do you know licence key? (Issue #9)
>
 
My MAC is: 40:91:51:58:A7:BC and Firmware is 2.5.4, please find my license password. THX
C2B45FA7A44E

**Comment by Alex-q-lab** [comment]
> > Удалось ли кому-нибудь решить проблему с лицензионным кодом? Похоже, мы приобрели копии оригинального устройства, и компания решила заблокировать их лицензионным кодом, который, похоже, недоступен! Есть ли способ прошить эти устройства другой прошивкой, которая позволит нам перепрофилировать их?
> 
> Если вам нужен код, отправьте мне сообщение или ответьте здесь, указав свой MAC-адрес.

Тоже столкнулся с такой ситуацией, необходимо было прошить и после пере прошивки при включении запрашивает лицензионный код. Ни где в инете не смог найти решение, может кто помочь? 
Mac: 40:91:51:58:57:ED прошивка HG V3.1.6

**Comment by Bledule** [comment]
Pošli MAC adresu na tenhle ***@***.*** a popros o kod
______________________________________________________________
> Od: "Alex-q-lab" ***@***.***>
> Komu: "GeekMagicClock/smalltv" ***@***.***>
> Datum: 08.10.2024 17:16
> Předmět: Re: [GeekMagicClock/smalltv] Do you know licence key? (Issue #9)
>
 
Удалось ли кому-нибудь решить проблему с лицензионным кодом? Похоже, мы приобрели копии оригинального устройства, и компания решила заблокировать их лицензионным кодом, который, похоже, недоступен! Есть ли способ прошить эти устройства другой прошивкой, которая позволит нам перепрофилировать их?
Если вам нужен код, отправьте мне сообщение или ответьте здесь, указав свой MAC-адрес.
Тоже столкнулся с такой ситуацией, необходимо было прошить и после пере прошивки при включении запрашивает лицензионный код. Ни где в инете не смог найти решение, может кто помочь?
 Mac: 40:91:51:58:57:ED прошивка HG V3.1.6

**Comment by Bledule** [comment]
ychj90 gmail.com <?restart=2#composeto>
ychj90 gmail.com
______________________________________________________________
> Od: "Alex-q-lab" ***@***.***>
> Komu: "GeekMagicClock/smalltv" ***@***.***>
> Datum: 08.10.2024 17:16
> Předmět: Re: [GeekMagicClock/smalltv] Do you know licence key? (Issue #9)
>
 
Удалось ли кому-нибудь решить проблему с лицензионным кодом? Похоже, мы приобрели копии оригинального устройства, и компания решила заблокировать их лицензионным кодом, который, похоже, недоступен! Есть ли способ прошить эти устройства другой прошивкой, которая позволит нам перепрофилировать их?
Если вам нужен код, отправьте мне сообщение или ответьте здесь, указав свой MAC-адрес.
Тоже столкнулся с такой ситуацией, необходимо было прошить и после пере прошивки при включении запрашивает лицензионный код. Ни где в инете не смог найти решение, может кто помочь?
 Mac: 40:91:51:58:57:ED прошивка HG V3.1.6

**Comment by Alex-q-lab** [comment]
Mac: 40:91:51:58:57:ED firmware HG V3.1.6 Do you know the license key?

**Comment by Bledule** [comment]
Kód na tvoji MAC adresu nemám, poslal jsem svoji MAC na email ychj90 gmail.com a do dvou dnů mi přišel kód
***@***.***
______________________________________________________________
> Od: "Alex-q-lab" ***@***.***>
> Komu: "GeekMagicClock/smalltv" ***@***.***>
> Datum: 08.10.2024 18:15
> Předmět: Re: [GeekMagicClock/smalltv] Do you know licence key? (Issue #9)
>
 
Mac: 40:91:51:58:57:ED firmware HG V3.1.6 Do you know the license key?

**Comment by Alex-q-lab** [comment]
Мой Mac: 40:91:51:58:57:ED firmware HG V3.1.6 Do you know the license key?

**Comment by GeekMagicClock** [comment]
For counterfeit products, please immediately apply for a refund and give a one-star review. After-sales issues related to counterfeit products are not accepted here. Please stop posting here, thank you! Please support orginal genuine products!
